package com.dengin.social.api;

import com.dengin.social.application.dto.AITrendResponse;
import com.dengin.social.application.service.TrendService;
import com.dengin.social.domain.service.AITrendGenerationService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * Trend REST Controller
 * 
 * Provides AI-generated profession trend endpoints for mobile app.
 * 
 * Endpoints:
 * - GET /api/trends/profession/{category} - Get trends for profession
 * 
 * Features:
 * - OpenRouter AI integration
 * - Turkish content generation
 * - 1-hour caching per profession
 * - Rate limiting: 100 requests/hour
 * - Authentication: Required
 * 
 * Mobile Integration:
 * - AITrendInsightCard component
 * - FeedScreen header
 * - Replaces mockTrends.ts
 * 
 * @see TrendService
 * @see AITrendGenerationService
 */
@RestController
@RequestMapping("/api/trends")
@RequiredArgsConstructor
@Slf4j
@Tag(name = "Trends", description = "AI-generated profession trend insights")
public class TrendController {
    
    private final TrendService trendService;
    
    /**
     * GET /api/trends/profession/{category}
     * Get AI-generated trends for specific profession category
     * 
     * Returns 3 Turkish trend titles generated by OpenRouter AI.
     * Results cached for 1 hour per profession.
     * 
     * Example Categories:
     * - MEDICAL: Sağlık ve Tıp
     * - LEGAL: Hukuk ve Avukatlık
     * - ENGINEERING: Mühendislik ve Teknoloji
     * - EDUCATION: Eğitim ve Öğretim
     * - SERVICE: Hizmet Sektörü
     * - CREATIVE: Yaratıcı ve Sanat
     * - BUSINESS: İş ve Finans
     * - OTHER: Diğer Alanlar
     * 
     * @param category Profession category (case-insensitive)
     * @return List of 3 AI-generated trend responses
     */
    @GetMapping("/profession/{category}")
    @Operation(
        summary = "Get AI trends for profession category",
        description = "Returns 3 AI-generated Turkish trend titles for specified profession category. " +
                     "Trends are generated using OpenRouter API and cached for 1 hour. " +
                     "Replaces mobile mockTrends.ts with dynamic content.",
        security = @SecurityRequirement(name = "Bearer Authentication")
    )
    @ApiResponses(value = {
        @ApiResponse(
            responseCode = "200",
            description = "Successfully retrieved trends",
            content = @Content(
                mediaType = "application/json",
                schema = @Schema(implementation = AITrendResponse.class)
            )
        ),
        @ApiResponse(
            responseCode = "400",
            description = "Invalid profession category"
        ),
        @ApiResponse(
            responseCode = "401",
            description = "Unauthorized - JWT token missing or invalid"
        ),
        @ApiResponse(
            responseCode = "429",
            description = "Rate limit exceeded (100 requests/hour)"
        ),
        @ApiResponse(
            responseCode = "500",
            description = "Internal server error - AI service unavailable (returns fallback trends)"
        )
    })
    public ResponseEntity<List<AITrendResponse>> getTrendsByProfession(
        @Parameter(
            description = "Profession category (MEDICAL, LEGAL, ENGINEERING, etc.)",
            required = true,
            example = "MEDICAL"
        )
        @PathVariable String category
    ) {
        log.info("GET /api/trends/profession/{} - Fetching AI trends", category);
        
        try {
            List<AITrendResponse> trends = trendService.getTrendsByProfessionName(category);
            
            log.debug("Returning {} trends for category: {}", trends.size(), category);
            return ResponseEntity.ok(trends);
            
        } catch (IllegalArgumentException ex) {
            log.warn("Invalid profession category: {}", category);
            return ResponseEntity.badRequest().build();
        }
    }
    
    /**
     * GET /api/trends/categories
     * Get all valid profession categories
     * 
     * Helper endpoint for mobile development/debugging.
     * Returns list of valid category values.
     * 
     * @return List of category names
     */
    @GetMapping("/categories")
    @Operation(
        summary = "Get all profession categories",
        description = "Returns list of valid profession category names for trend generation.",
        security = @SecurityRequirement(name = "Bearer Authentication")
    )
    @ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "Successfully retrieved categories"),
        @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    public ResponseEntity<List<String>> getProfessionCategories() {
        log.debug("GET /api/trends/categories");
        
        List<String> categories = List.of(
            "MEDICAL", "LEGAL", "ENGINEERING", "EDUCATION",
            "SERVICE", "CREATIVE", "BUSINESS", "OTHER"
        );
        
        return ResponseEntity.ok(categories);
    }
}
